name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  publish-aws-s3:
    name: Publish to AWS S3
    runs-on: 'ubuntu-latest'
    environment: 'builds.guardrailsjs.com.s3.amazonaws.com'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: |
          git config --global user.email "release@guardrailsjs.com"
          git config --global user.name "guardrails-lang"
          npm run publish:aws
        env:
          S3_BUCKET_NAME: "builds.guardrailsjs.com"
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
